name: rentorown
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy-financial
  - matplotlib
  - python-dateutil
  - pip
  - jupyterlab
  - ipywidgets
  - pip:
      - altair_recipes
      - .
